created: 2026-04-09T15:54:44.659Z
updated: 2026-04-09T15:54:44.830Z
update_count: 2
last_field: diagram
kind: nested-class
title: web
children:
  - api-layer
  - components
  - pages
  - router
  - stores
parentPath: []
