created: 2026-04-09T15:55:18.223Z
updated: 2026-04-09T15:55:18.386Z
update_count: 2
last_field: diagram
kind: nested-class
title: gateway
children:
  - db
  - middleware
  - routes
  - scheduler
  - services
parentPath: []
